[colors]
ansi = [
    "#0A0A12",
    "#C25B5B",
    "#8BAA82",
    "#E6C27A",
    "#6270A8",
    "#9A7398",
    "#95B3B0",
    "#E4DED2",
]
background = "#0A0A12"
brights = [
    "#2A2A38",
    "#E08A66",
    "#8BAA82",
    "#E6C27A",
    "#6270A8",
    "#9A7398",
    "#95B3B0",
    "#FFF8F2",
]
cursor_bg = "#E4DED2"
cursor_border = "#E4DED2"
cursor_fg = "#0A0A12"
foreground = "#E4DED2"
selection_bg = "#E4DED2"
selection_fg = "#0A0A12"

[metadata]
name = "OccultUmbral"
