[colors]
ansi = [
    "#FFF8F2",
    "#C25B5B",
    "#8BAA82",
    "#E6C27A",
    "#6270A8",
    "#9A7398",
    "#95B3B0",
    "#0A0A12",
]
background = "#FFF8F2"
brights = [
    "#3A3A4A",
    "#E08A66",
    "#8BAA82",
    "#E6C27A",
    "#6270A8",
    "#9A7398",
    "#95B3B0",
    "#0A0A12",
]
cursor_bg = "#0A0A12"
cursor_border = "#0A0A12"
cursor_fg = "#FFF8F2"
foreground = "#0A0A12"
selection_bg = "#0A0A12"
selection_fg = "#FFF8F2"

[metadata]
name = "OccultUmbral"
