theme = "noctalia"

[editor]
bufferline = "always"
line-number = "relative"
mouse = false
editor-config = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
left = ["mode", "spinner", "diagnostics"]
right = ["position", "separator", "total-line-numbers"]
separator = "|"

[editor.indent-guides]
character = "|"
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
space = ":fmt"
tab = ":buffer-next"
