[[language]]
auto-format = false
name = "nix"

[language-server.nixd]
args = ["--semantic-tokens=true"]
command = "nixd"

[language-server.nixd.config.nixd.formatting]
command = ["alejandra"]

[language-server.nixd.config.nixd.nixpkgs]
expr = "import (builtins.getFlake (toString /home/salivala/nixos-config)).inputs.nixpkgs { }"

[language-server.nixd.config.nixd.options.nixos]
expr = "(builtins.getFlake (toString /home/salivala/nixos-config)).nixosConfigurations.desktop.options"

[language-server.nil]
command = "nil"

[language-server.nil.config.nil.formatting]
command = ["alejandra"]

[[language]]
name = "javascript"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "jsx"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }

[language.debugger]
command = "lldb-dap"
name = "lldb-dap"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ {name = "binary", completion = "filename" }]
args = {program = "{0}", cwd = "${1}"}

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = ["pid"]
args = {pid = "${0}"}

[[language]]
name = "go"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "c"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "java"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "html"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "css"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "scss"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
